// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDehbSh0_z8PU9SVqRph38hLv5b5Wy9v7I',
    appId: '1:718792820556:web:aa08dd4c2c82f8b142b1e9',
    messagingSenderId: '718792820556',
    projectId: 'flutter-libros',
    authDomain: 'flutter-libros.firebaseapp.com',
    storageBucket: 'flutter-libros.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUdiYjSJepurqGOSuG_KfT_egKeF8Zvoc',
    appId: '1:718792820556:android:8f8d914f73d43cb242b1e9',
    messagingSenderId: '718792820556',
    projectId: 'flutter-libros',
    storageBucket: 'flutter-libros.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4CPsJTeP_Np-_DGszWxee1uWza6zujL0',
    appId: '1:718792820556:ios:091faecce4a3971a42b1e9',
    messagingSenderId: '718792820556',
    projectId: 'flutter-libros',
    storageBucket: 'flutter-libros.appspot.com',
    iosClientId: '718792820556-qikeqf4i761fuqpksa4i7g6qj23t2806.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4CPsJTeP_Np-_DGszWxee1uWza6zujL0',
    appId: '1:718792820556:ios:091faecce4a3971a42b1e9',
    messagingSenderId: '718792820556',
    projectId: 'flutter-libros',
    storageBucket: 'flutter-libros.appspot.com',
    iosClientId: '718792820556-qikeqf4i761fuqpksa4i7g6qj23t2806.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
